import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavCompo from "./components/Navbar";
import FooterCompo from "./components/Footer";
import "flowbite/dist/flowbite.css";
import WhatsAppLog from "./components/whatsAppLog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Two Prints",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <NavCompo/>
        {children}
        <WhatsAppLog/>
        <FooterCompo/>
      </body>
    </html>
  );
}
